Repository playframework/play-grpc, pull requests merged in 2019-01, with the labels that each got.

#31 Refactors docs into index and byte-size pages
  .gitignore
  docs/src/main/paradox/consuming-grpc.md
  docs/src/main/paradox/gradle-support.md
  docs/src/main/paradox/index.md
  docs/src/main/paradox/play-framework.md
  docs/src/main/paradox/serving-grpc.md
Labels: review

#32 Various mini fixes
  .travis.yml
  build.sbt
  play-interop-test-java/src/test/scala/play/grpc/PlayJavaRouterSpec.scala
  play-interop-test-scala/src/main/scala/controllers/MyController.scala
  play-interop-test-scala/src/test/scala/play/grpc/PlayScalaRouterSpec.scala
  project/Dependencies.scala
  project/plugins.sbt
Labels: merge-when-green

#33 Support multiple HTTP/2 endpoints per server
  play-testkit/src/main/java/play/grpc/testkit/JavaAkkaGrpcClientHelpers.java
  project/Dependencies.scala
  project/ProjectExtensions.scala
Labels: ready

#37 Cleanup and clarify releasing
  RELEASING.md
Labels: merge-when-green

#38 Setup TechHub ping
  .travis.yml
Labels: merge-when-green
